### ISSUE TITLE
Bug: Search Bar Hidden Behind Profile Header on Mobile Devices

### ISSUE THREAD

**Issue by mouad-dadda** [open-sauced/app#4076] opened 2024-09-02 15:31 UTC
### Describe the bug

 On mobile devices, the ` search bar` is being hidden behind the profile header. This makes it difficult for users to access the search functionality, negatively impacting usability on smaller screens.

![Screenshot 2024-09-02 162628](https://github.com/user-attachments/assets/f939229f-98dc-426d-8279-1373c78a91a8)

### Steps to reproduce

Access the profile page on a mobile device  .

Scroll to the top of the page where the search icon is located , click on it.

Observe that the search bar is obscured by the profile header, making it difficult or impossible to use.

**Comment by shubhamchasing** [comment] 2024-09-02 18:29
.take

**Comment by nickytonline** [comment] 2024-09-03 14:32
Duplicate of #3614

**Closed by nickytonline** 2024-09-03 14:32 UTC
Labels: 🐛 bug, 👀 needs triage
