### ISSUE TITLE
Bug: no default pages for the tools

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#2223] opened 2023-11-28 19:30 UTC
### Describe the bug

if you go to this https://app.opensauced.pizza/javascript page, you will encounter the loading state of the app, which is not the optimal case for this. 

### Sugesstion

I think having a default value to open the dashboard and the tools we have is a good solution. 

### Steps to reproduce

1. go to https://app.opensauced.pizza/javascript
2. Tada! 

Related to: https://github.com/open-sauced/app/issues/2222 and https://github.com/open-sauced/app/issues/2185

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by FatumaA** [comment] 2024-03-18 13:34
Hi,
I can't reproduce this. The app redirects to the correct place. 
Please confirm this then we can close the issue.

**Comment by nickytonline** [comment] 2024-03-19 00:05
This relates to #2600. @zeucapua will be working on #2600 this sprint.

**Closed** 2024-08-21 15:46 UTC
Labels: 🐛 bug, 👀 needs triage
