### ISSUE TITLE
Bug: StarSearch for Workspaces not consistently giving results

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#3769] opened 2024-07-24 17:13 UTC
### Describe the bug

When I ask starsearch a question in workspaces, sometimes it just "thinks" about it (I get the loading animation) and then nothing happens. There's no indication on the front-end that it timed out or won't give results, so I need to ask again when I realize it's happening.

### Steps to reproduce

I haven't been able to consistently reproduce this. You can try it by going to one of your workspaces and asking about lottery factor. That's the question I most consistently get the error.

**Comment by nickytonline** [comment] 2024-07-24 21:26
I'll be pairing with @jpmcb on this, but one thing I noticed so far is the readable stream of server sent events (SSEs) finishes almost immediately, so the code assume the stream is done. This seems like a regression.

I've also noticed that the stream of SSEs comes in, looks like it's done, then it kickstarts again.

Not sure what's up yet, but both these scenarios occur on StarSearch for workspaces and regular StarSearch.

**Comment by BekahHW** [comment] 2024-07-25 15:29
@bdougie I chatted with Nick about it this morning and I haven't been able to reproduce it today. Every time I tried to record it yesterday it worked. I'm still trying to figure it out.

**Comment by BekahHW** [comment] 2024-07-25 15:50
@nickytonline I went through some of the videos I recorded yesterday and I found an example. Again, I can't replicate it though. 

https://github.com/user-attachments/assets/8fccf8b4-078c-4082-8205-72cfe4296fde

**Comment by nickytonline** [comment] 2024-08-03 14:06
This should be sorted out now that there have been improvements to the StarSearch backend made by @jpmcb. I'm going to go ahead and close this for now as I can no longer replicate this. Feel free to reopen @BekahHW if you still exhibit this behaviour.

**Closed** 2024-08-03 14:07 UTC
Labels: 🐛 bug, 👀 needs triage
