### ISSUE TITLE
Bug: The pagination on the contributors page doesn't work properly

### ISSUE THREAD

**Issue by StandinKP** [open-sauced/app#3934] opened 2024-08-13 00:11 UTC
### Describe the bug

I am trying to access https://app.opensauced.pizza/workspaces/cff3f17b-f052-4686-85af-72971009136b/contributor-insights/545c756a-39e0-4361-b516-9610cb413959/overview
Even if I go to any page, it shows me the first page itself.

I am using: 
MacOS 15
Arc browser
Based in India
No problem with network as other websites work properly as expected

### Steps to reproduce

1. Go to https://app.opensauced.pizza/workspaces/cff3f17b-f052-4686-85af-72971009136b/contributor-insights/545c756a-39e0-4361-b516-9610cb413959/overview
2. Click on any page number at the bottom of the table

**Comment by shubhamchasing** [comment] 2024-08-18 14:08
I have checked it on

- Ubuntu 20 and Windows 11 (both on chrome) 
- As Authenticated and Guest user

it is working fine.
I think it would be better if you upload a screen recording.

**Comment by nickytonline** [comment] 2024-08-18 15:48
I just went to the link you provided and everything is working fine.

This was already fixed and confirmed fixed in #3945. Marking this as a duplicate of #3944.

As @shubhamchasing mentions, please provide a reproduction if this is not the case.

**Closed** 2024-08-18 15:48 UTC
Labels: 🐛 bug, 👀 needs triage
