### ISSUE TITLE
Bug: contributions curve over extends top of graph and gets cut off

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1285] opened 2023-06-22 15:55 UTC
### Describe the bug

When looking at the contributions graph, in this case, the graph line sort of bubbles over the view of the graph:

![Screenshot 2023-06-22 at 8 36 28 AM](https://github.com/open-sauced/insights/assets/23109390/bc64e0cc-6682-461f-bad6-4924030636e9)

Is this expected behavior? May be related to https://github.com/open-sauced/insights/issues/281 ?

### Steps to reproduce

Easily viewable on my page: https://insights.opensauced.pizza/user/jpmcb/contributions

Seems to be the case on both Chrome and Firefox

### Browsers

Firefox

### Additional context (Is this in dev or production?)

Prod

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment] 2023-08-18 18:55
This unfortunately still looks like a problem:

![Screenshot 2023-08-18 at 12 54 54 PM](https://github.com/open-sauced/insights/assets/23109390/dfcea22e-dacb-4f1e-9d87-2ee7cf83a0ee)

**Comment by brandonroberts** [comment] 2024-03-01 20:03
Closing as a duplicate of https://github.com/open-sauced/engineering/issues/108

**Closed by brandonroberts** 2024-03-01 20:03 UTC
Labels: 🐛 bug, released, released on @beta
