### ISSUE TITLE
Bug: Menu for a highlight won't open so can't edit highlight

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2039] opened 2023-11-02 13:01 UTC
### Describe the bug

Go to one of your highlights. Try clicking on the three dots menu beside the X/Twitter button. The menu opens and closes very quickly.

### Steps to reproduce

Here's the issue in action when I try to edit one of my own highlights.

![CleanShot 2023-11-02 at 08 57 24](https://github.com/open-sauced/app/assets/833231/36921c4c-c228-4983-836e-114563e8b379)

This looks similar to the date picker issue we had in Safari @OgDev-01, but this one is happening in Chromium based browsers.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment] 2023-11-02 15:10
I think this is a duplicate of #1896

**Closed** 2023-11-02 15:47 UTC
Labels: duplicate, 🐛 bug, high-priority
