### ISSUE TITLE
Bug: Elements overlap with searchbox in mobile viewport

### ISSUE THREAD

**Issue by harshit078** [open-sauced/app#4146] opened 2024-09-28 20:33 UTC
### Describe the bug

- When using the searchbox in mobile viewports, many components of the page doesn't go into blur and are accessible.
- Search Bar goes behind card element in the main page making it inaccessible.

## Current Behaviour

<img width="434" alt="Screenshot 2024-09-29 at 1 31 57 AM" src="https://github.com/user-attachments/assets/e65d4df9-e8c0-41be-a075-4fd973b3f3b6">

<img width="428" alt="Screenshot 2024-09-29 at 1 52 03 AM" src="https://github.com/user-attachments/assets/5b2215fe-1ed0-46d3-80e4-1f1a7307fa14">
<img width="436" alt="Screenshot 2024-09-29 at 1 54 39 AM" src="https://github.com/user-attachments/assets/a558055f-096d-4e4f-a155-1c2c6b9c51c8">

## Expected Behaviour

<img width="435" alt="Screenshot 2024-09-29 at 1 58 01 AM" src="https://github.com/user-attachments/assets/5375dd78-c894-4ba5-9812-77e2e317b554">

### Steps to reproduce

1. Switch to mobile view in Inspect tab
2. Search using searchbox

**Comment by Bashamega** [comment] 2024-10-01 04:39
I would like to work on this

**Comment by nickytonline** [comment] 2024-10-01 09:25
Closing as this is a duplicate of #3614

**Closed** 2024-10-01 09:25 UTC
Labels: 🐛 bug, 👀 needs triage
