### ISSUE TITLE
Feature: add menu to large screens

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#1455] opened 2023-07-31 21:40 UTC
### Type of feature

🍕 Feature

### Current behavior

The large screens right now is hiding the contributors and last 30 days options in repositories tables, it would be great to have an option to open them as a row similar to the small screens. 

The table defaults values: 
![image](https://github.com/open-sauced/insights/assets/18273833/f81468ae-602f-4a38-93cb-efb1ad9914df)

Table on large screens (last 30 days, and contributors are hidden): 
![image](https://github.com/open-sauced/insights/assets/18273833/b3e0c671-fb02-4582-be55-d943c51dfbb9)

In small screens right now you can see that there are a button to open the table and add the related hidden columns: 
![image](https://github.com/open-sauced/insights/assets/18273833/857c317a-07a3-47dc-87a5-63df5e1b84c7)

 

### Suggested solution

Implement the small screen logic to large screens to show the button and show the hidden attributes.

### Additional context

Related to https://github.com/open-sauced/insights/pull/1437

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment] 2023-08-01 10:16
@bdougie since this has been added to the roadmap, does that mean we can remove needs triage? (I do not remove needs triage from the issues that I opened myself, I need a second opinion)

**Comment by dev-phantom** [comment] 2023-08-03 19:59
I guess reducing the padding x on the table on the large screen and displaying the contributors and last 30 day will fix this

what do you think about this solution @bdougie?

**Comment by bdougie** [comment] 2023-08-03 20:27
> @bdougie since this has been added to the roadmap, does that mean we can remove needs triage? (I do not remove needs triage from the issues that I opened myself, I need a second opinion)

No, that is to make it easier to know what is needed. I selected all issues and added them because that had not been for other issues when the label was removed. Everything needs to be on the roadmap with a milestone. 

I still need to see the value for this. This is a nice to have, but I'd argue very few users have noticed what you have pointed out. 

> I guess reducing the padding x on the table on the large screen and displaying the contributors and last 30 day will fix this

If we go with @dev-phantom's solution it doesn't quite solve the problem. The problem is that we don't know if that data is even useful. I think we can keep the needs-triage label on this for now and aim to keep the conversation open. 

Not a solution, but a better suggestion is removing spam as a column. This is not a solution, because the real question there is, "Can we track spam in a way that it is not alway `-`?"

**Comment by 289Volts** [comment] 2023-10-02 12:09
> > @bdougie since this has been added to the roadmap, does that mean we can remove needs triage? (I do not remove needs triage from the issues that I opened myself, I need a second opinion)
> 
> No, that is to make it easier to know what is needed. I selected all issues and added them because that had not been for other issues when the label was removed. Everything needs to be on the roadmap with a milestone.
> 
> I still need to see the value for this. This is a nice to have, but I'd argue very few users have noticed what you have pointed out.
> 
> > I guess reducing the padding x on the table on the large screen and displaying the contributors and last 30 day will fix this
> 
> If we go with @dev-phantom's solution it doesn't quite solve the problem. The problem is that we don't know if that data is even useful. I think we can keep the needs-triage label on this for now and aim to keep the conversation open.
> 
> Not a solution, but a better suggestion is removing spam as a column. This is not a solution, because the real question there is, "Can we track spam in a way that it is not alway `-`?"

I thought about a solution now. What if the table is actually scrollable? Since the table is probably in a container, it can overflow out of the container and scroll to the left

**Comment by brandonroberts** [comment] 2024-03-01 20:11
Closing as resolved with the move to workspaces that includes a sidebar that we will continue rolling out the rest of the app

**Closed by brandonroberts** 2024-03-01 20:11 UTC
Labels: 💡 feature
