### ISSUE TITLE
Bug: repo logo overlaps search bar in mobile view on repo pages

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#3986] opened 2024-08-19 17:49 UTC
### Describe the bug

On mobile view, within repo pages, when searching, notice how the repo logo overlaps the search bar:

![Screenshot 2024-08-19 at 11 46 20 AM](https://github.com/user-attachments/assets/98b4f300-7112-4855-aa66-7ef49dd56566)

Probably a z index problem: the search bar should be the most forefront thing on the repo page when searching.

### Steps to reproduce

1. Go to a repo page using mobile view (use browser dev tools): https://app.opensauced.pizza/s/kubernetes/kubernetes
2. Hit the search icon
3. Notice the icon overlaps the search results / search bar

**Comment by SURAJ-SHARMA27** [comment] 2024-08-19 18:17
.take

**Comment by SURAJ-SHARMA27** [comment] 2024-08-19 19:43
I have noticed the same issue with two things: the 'I want this Now' button and the 'Last Updated' section both overlap the backdrop of the search bar. Should I fix them in this PR, or should I raise an issue first?

![image](https://github.com/user-attachments/assets/19c9ac12-ff28-48da-a45d-bc7cf0e20d97)

![image](https://github.com/user-attachments/assets/e82866cb-7507-4aa1-a6c6-d3e886eaaec5)

**Comment by jpmcb** [comment] 2024-08-19 19:46
> Should I fix them in this PR, or should I raise an issue first?

If it's a similar fix on the repo page, go ahead and fix it!

**Comment by brandonroberts** [comment] 2024-08-21 15:31
Duplicate of https://github.com/open-sauced/app/issues/3614. Let's track there instead

**Closed** 2024-08-27 19:21 UTC
Labels: good first issue, 🐛 bug
