### ISSUE TITLE
Bug: Trying to sync a team requires logout

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2428] opened 2024-01-07 00:16 UTC
### Describe the bug

Frequently when I'm trying to sync a team to a list, I get this error:

<img width="440" alt="image" src="https://github.com/open-sauced/app/assets/34313413/dbd9d1f9-94d6-4a2d-b3b9-a46f88f97b42">

The solution is to log out and log back in again. 

### Steps to reproduce

1. Go to List
2. Create New List
3. Choose and organization
4.  See error

This often happens when I'm already logged in for a while, but today it happened right after I freshly logged in. 

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment] 2024-01-08 13:40
I think this is kind of related to the github token timeout with supabase... Just thinking out loud: Looking at https://github.com/supabase/gotrue-js/issues/131 from supabase, if a `provider_refresh_token` is obtainable it would be a potential fix for this issue across the app. thoughts @open-sauced/engineering?

**Comment by brandonroberts** [comment] 2024-01-08 14:33
Yes, we would need to get the `provider_refresh_token` and use it to refresh the token in place. I saw a post in the issue that may work. I'll take another look

**Comment by jpmcb** [comment] 2024-01-08 15:31
Note: we have the same problem when generating AI text in highlights: https://github.com/open-sauced/app/issues/1440

My hypothesis is we need to probably fix this app wide since we'll keep hitting sharp edges with OpenSauced <--> Supabase <--> GitHub integration

**Comment by brandonroberts** [comment] 2024-01-12 19:58
Did some investigation here, and `provider_refresh_token` is available but only when using a **GitHub App**, but not a **GitHub OAuth App**, which is what we're using for authentication. I created a repo here

https://github.com/brandonroberts/supabase-github-app-auth

Steps to reproduce:
1. Clone the repo
2. Install the dependencies
3. Run the dev server `npm run dev`
4. Navigate to http://localhost:3000/login
5. Open Browser Devtools
6. Click on the "Login" button
7. Login with the GitHub prompt
8. After redirected back to http://localhost:3000, see the browser console and look at the session data
9. Note the presence of the `provider_refresh_token` value instead of being `null`

<img width="220" alt="Screenshot 2024-01-12 at 1 47 17 PM" src="https://github.com/open-sauced/app/assets/42211/eb115af9-92de-41de-835b-b9ab66c5e6a9">

**Comment by brandonroberts** [comment] 2024-07-10 16:55
We removed organization permissions as a requirement

**Closed by brandonroberts** 2024-07-10 16:55 UTC
Labels: 🐛 bug, high-priority
