### ISSUE TITLE
feat: Make Workspace org importing not user specific. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2874] opened 2024-03-05 20:20 UTC
I'd love to see all orgs searchable in this list. 

![Screen Shot 2024-03-05 at 12 12 23 PM](https://github.com/open-sauced/app/assets/5713670/8671a6a0-7e11-42aa-8553-b5410e6c1842)

## Problem

I cannot demo worskpaces by importing an organization with someone. I can only watch them do it.

## Solution

If there is a technical limitation I am unaware and happy to close as won't fix, but the import for orgs on repository insights allow me to type an org and import. I'd love to follow that strategy in workspaces. 

![Screen Shot 2024-03-05 at 12 18 54 PM](https://github.com/open-sauced/app/assets/5713670/94692020-6924-4fdc-95be-af1b7e8ffd65)

**Comment by jpmcb** [comment] 2024-03-08 22:13
Duplicate of: https://github.com/open-sauced/app/issues/2836

Nick wasn't sure that was possible via the GitHub API: worth investigating.

**Comment by nickytonline** [comment] 2024-03-18 19:49
When I looked at this initially, there didn't appear to be a GH API endpoint to search for orgs. You could only get the orgs you belong to. It doesn't prevent us from importing repos from a non-user org, but as far as I know, we can search orgs on GH.

**Comment by bdougie** [comment] 2024-03-19 00:05
> When I looked at this initially, there didn't appear to be a GH API endpoint to search for orgs. You could only get the orgs you belong to. It doesn't prevent us from importing repos from a non-user org, but as far as I know, we can search orgs on GH.

I caught up with Nick via Slack. We can prioritize amongst some other Workspace follow up issues.

**Closed** 2024-03-20 02:18 UTC
Labels: core team work, workspaces
