### ISSUE TITLE
Bug: redirect workspace urls that don't exist

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2769] opened 2024-02-26 18:37 UTC
### Describe the bug

If a user types in a workspace url that doesn't exist, it should redirect to their personal workspace. 

### Steps to reproduce

1. Use this URL https://app.opensauced.pizza/workspaces/feed 
2. See this
![image](https://github.com/open-sauced/app/assets/34313413/9150c1a6-ca6f-45f1-91d3-4a7d4a552f54)

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment] 2024-02-26 22:13
Duplicate of #2723

**Closed by nickytonline** 2024-02-26 22:13 UTC
Labels: 🐛 bug, 👀 needs triage
