### ISSUE TITLE
Bug: hydration errors on Insight Page(New)

### ISSUE THREAD

**Issue by shubhamchasing** [open-sauced/app#2498] opened 2024-01-19 08:23 UTC
### Describe the bug

I saw the hydration errors while working on [#2474](https://github.com/open-sauced/app/issues/2474)
Also checked on latest beta release it is there
so creating new issue

On local

![Screenshot from 2024-01-18 01-17-57](https://github.com/open-sauced/app/assets/106425076/6fc62044-ae62-4aec-8e13-111a89c372e5)

On beta live
![Screenshot from 2024-01-18 01-16-43](https://github.com/open-sauced/app/assets/106425076/26393c3e-1949-40ba-b045-f97ecb31a7ec)

### Steps to reproduce

1 Go to insight page https://app.opensauced.pizza/hub/insights
2 Click New Insight
3 See console

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment] 2024-01-24 12:41
Duplicate of #2520.

**Closed** 2024-01-24 12:41 UTC
Labels: 🐛 bug, 👀 needs triage
