### ISSUE TITLE
Bug: insights overview page not responsive to small screens

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1799] opened 2023-10-04 17:03 UTC
### Describe the bug

![Screenshot 2023-10-04 at 10 59 48 AM](https://github.com/open-sauced/app/assets/23109390/402b2e45-c1da-433c-811e-f9d87424caae)

This was a screenshot from chrome where the width was about 1000 px. Notice how the buttons on the right spill over and generally, as the screen gets smaller, the entire structure collapses.

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/hub/insights
2. Create a few insight pages
3. Make the screen smaller via the dev tools or with the window
4. Notice the buttons overlap to the right and the structure of the design falls apart

### Browsers

Chrome, Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by vedant-z** [comment] 2023-10-04 22:03
@jpmcb I am not able to reproduce the issue. It seems to be working fine on my device.

Is it that width or dimensions I have set are incorrect?

![image](https://github.com/open-sauced/app/assets/93431609/3997dceb-af28-4c2a-8f7e-2590efa0109d)

**Comment by babblebey** [comment] 2023-10-07 03:09
Kindly review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for information on how to assign yourself to the issue. 

🍕

**Comment by Krishnakalani111** [comment] 2023-10-07 08:18
.take

**Comment by jpmcb** [comment] 2023-10-07 15:57
@vedant-z - yeah this still looks to be a problem: 1000px wide seems to make it happen

<img width="1427" alt="Screenshot 2023-10-07 at 10 55 06 AM" src="https://github.com/open-sauced/app/assets/23109390/986e7f07-035a-4c09-9aff-28073afc4141">

But it seems it might have to do with the content of each page's title / data:

<img width="1428" alt="Screenshot 2023-10-07 at 10 56 50 AM" src="https://github.com/open-sauced/app/assets/23109390/f652d3a6-488f-42b5-8cd5-0345158619dd">

Here I made one titled "woof" (a very short title) and it does not cause the buttons to spill out or look weird

**Comment by brandonroberts** [comment] 2024-08-21 15:54
Closing as part of move to workspaces

**Closed by brandonroberts** 2024-08-21 15:54 UTC
Labels: 🐛 bug, 👀 needs triage
