### ISSUE TITLE
Bug: Duplicate Notifications for follows

### ISSUE THREAD

**Issue by diivi** [open-sauced/app#1642] opened 2023-08-30 22:49 UTC
### Describe the bug

![image](https://github.com/open-sauced/app/assets/41837037/7bcd18e5-36b5-4060-9fb0-d5f5ffd1f95b)
5 notifs saying the same thing (not even a repeatable event) unless @ThePiyushAggarwal followed me, unfollowed me and followed me again a few times.

### Steps to reproduce

1. Go to your notifs

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment] 2023-08-30 23:09
This is a duplicate of https://github.com/open-sauced/app/issues/1615

**Closed** 2023-08-30 23:10 UTC
Labels: duplicate, 🐛 bug

**Comment by diivi** [comment] 2023-08-31 12:32
I saw that issue, but I thought this might be a different one. Since in that case, the user might actually have created multiple highlights. But in this case, it's unlikely that they followed me so many times. Maybe this is an error on the backend?

**Comment by bdougie** [comment] 2023-08-31 13:49
> I saw that issue, but I thought this might be a different one. Since in that case, the user might actually have created multiple highlights. But in this case, it's unlikely that they followed me so many times. Maybe this is an error on the backend?

The backend needs to take in a few considerations. That can all be discussed in the other issue.
