### ISSUE TITLE
Bug:  Contribution button not working

### ISSUE THREAD

**Issue by Ezzywealth** [open-sauced/app#2692] opened 2024-02-16 19:14 UTC
### Describe the bug

When i try to view the details of a contributor on the `https://app.opensauced.pizza/user/eoigal?tab=contributions` page, i observed that the contribution tab doesn't show when a user clicks the contribution tab button.

![Screenshot 2024-02-16 201201](https://github.com/open-sauced/app/assets/86690432/1457d433-1656-4ac9-a02f-b44652007706)

### Steps to reproduce

1. Go to https://app.opensauced.pizza/user/eoigal?tab=contributions
2. Click on the contribution tab
3. No user experience

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Ezzywealth** [comment] 2024-02-16 19:16
.take

**Comment by takanome-dev** [comment] 2024-02-17 10:23
cc @open-sauced/engineering, this looks like a regression. Tried to investigate it but have no clue why it is not working and what may be the cause.


https://github.com/open-sauced/app/assets/79809121/af9d0fc1-7b8e-4b02-a29c-9214c3b7e139

**Comment by brandonroberts** [comment] 2024-02-19 21:05
Closing as a duplicate of https://github.com/open-sauced/app/issues/2656

**Closed by brandonroberts** 2024-02-19 21:05 UTC
Labels: 🐛 bug, 👀 needs triage, high-priority
