### ISSUE TITLE
Bug: Newsletter form overflow

### ISSUE THREAD

**Issue by Code-Victor** [open-sauced/app#1791] opened 2023-10-03 09:58 UTC
### Describe the bug

The newsletter form on the insights [page](https://insights.opensauced.pizza/feed) overflows on medium screen sizes, while it looks right on larger screens. See the images below for comparison:

<img width="230" alt="image" src="https://github.com/open-sauced/app/assets/63613078/f38b776b-4897-4346-bd04-79900f820cd5">
<img width="230" alt="image" src="https://github.com/open-sauced/app/assets/63613078/8ad1a4b7-f954-4518-8660-a65c13bd8c90">

### Steps to reproduce

1. Click on the inspect tools.
2. Toggle the device toolbar (Ctrl + Shift + M on Chrome, Windows).
3. Change the dimensions to responsive and check how the newsletter form looks from 1024px breakpoint to 1480px, which is between the lg and 2xl (custom) breakpoints of the project.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment] 2023-10-03 12:12
Thanks for opening the issue @Code-Victor! There is already an issue for this and someone is assigned to it.

**Comment by nickytonline** [comment] 2023-10-03 12:12
Duplicate of #1729.

**Comment by nickytonline** [comment] 2023-10-03 12:19
Meant to mark this as not planned.

**Comment by nickytonline** [comment] 2023-10-03 12:20
Duplicates are of #1729.

**Closed** 2023-10-03 12:26 UTC
Labels: 🐛 bug, 👀 needs triage
