### ISSUE TITLE
Bug: input on delete list doesn't clear from previous delete

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#1938] opened 2023-10-18 13:25 UTC
### Describe the bug

When I delete a list, I have to type in the name of the list. However, the name of the list I previously deleted is still in the input.

### Steps to reproduce

1. To reproduce this, you need to have previously deleted another list. So start there.
2. Go to your lists and try to delete a different list of a different name. 
3. Notice that the previous word you typed to delete the list now appears in the input on the modal.

![image](https://github.com/open-sauced/app/assets/34313413/79d5eb2b-450f-4e3a-a26c-f66bc5160948)

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment] 2023-10-18 13:43
Duplicate of #1848

**Comment by jpmcb** [comment] 2023-10-18 18:39
Closing since this is duplicate of #1848 and has been resolved on https://beta.app.opensauced.pizza/. Should show up on the production app once we cut that over from beta!

**Closed by jpmcb** 2023-10-18 18:39 UTC
Labels: good first issue, 🐛 bug, ⚡️ easy win
