### ISSUE TITLE
Feature: allow for Org import from any org

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#2836] opened 2024-03-01 01:23 UTC
### Type of feature

🍕 Feature

### Current behavior

Currently, org import for workspaces only works for orgs that I'm in, not for other orgs I want to track. Example:

![Screenshot 2024-02-29 at 6 22 31 PM](https://github.com/open-sauced/app/assets/23109390/2cb0f2d3-5e28-4cfb-915c-4e67046ff726)

### Suggested solution

It's be really great to be able to track other orgs I'm not in so I don't have to manually import all those orgs reps.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by isabensusan** [comment] 2024-03-18 19:49
duplicate of #2874

**Closed by isabensusan** 2024-03-18 19:49 UTC
Labels: 💡 feature, 👀 needs triage, workspaces
