### ISSUE TITLE
Bug: Workspace Switcher and Add Insight outside of sidebar when Insight pages have title that falls outside of sidebar

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2882] opened 2024-03-06 00:33 UTC
### Describe the bug

Currently, I'm using Chrome and MacOS, and the workspace switcher and Add insight button are outside of the sidebar bc my Contributor Insights title falls outside of the sidebar..

Screen Recording 2024-03-05 at 7.17.00 PM

### Steps to reproduce

1. Go to your workspace on chrome
2. Create a contributor insight: OpenSauced Hacktoberfest Contributors (or just a really long title). See the icons shift.
![image](https://github.com/open-sauced/app/assets/34313413/53ce1e3e-a2c9-4a3f-a90c-d214ea32c165)

### Browsers

Chrome

### Additional context (Is this in dev or production?)

prod

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment] 2024-03-06 01:30
I think this is because one of your insight page names is really long which I thought was fixed in https://github.com/open-sauced/app/issues/2728

Maybe a regression, would be good to fix before release

**Comment by BekahHW** [comment] 2024-03-06 13:22
@zeucapua do you have time to work on this?

**Closed** 2024-03-11 18:43 UTC
Labels: 🐛 bug, 👀 needs triage, workspaces
