### ISSUE TITLE
Bug:  Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by priyankarpal** [open-sauced/app#2442] opened 2024-01-09 06:00 UTC
### Describe the bug

After running the app locally, if you open the console, you will notice an issue related to the missing 'key' prop.

we have to fix the issue 

![image](https://github.com/open-sauced/app/assets/88102392/17ba8d4a-162b-4182-a715-1b6926768fa3)

### Steps to reproduce

- run the app locally 
- open the console 
- you will see the issue

### Browsers

Other (add additional context)

### Additional context (Is this in dev or production?)

dev

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment] 2024-01-09 09:32
Thanks for opening this issue @priyankarpal! What page are the console errors appearing on?

**Comment by ThePiyushAggarwal** [comment] 2024-01-09 10:11
Wherever this component `components/atoms/SkeletonLoader/skeleton-wrapper.tsx` is used, the error should be there.
Because the `index` variable from `map` function hasn't been used.
Providing the `div`s inside, the `key` prop with `index` value should fix it wherever it is used.

![image](https://github.com/open-sauced/app/assets/27003616/15f90b3f-3af5-412f-a6be-65429ee8ce5a)

**Comment by a0m0rajab** [comment] 2024-01-09 11:29
@ThePiyushAggarwal, thanks for the input; your solution is the correct programmatically, but knowing the page would be helpful during the PR review to understand if the issue is solved or not and test it properly.

**Comment by priyankarpal** [comment] 2024-01-09 13:23
> Wherever this component `components/atoms/SkeletonLoader/skeleton-wrapper.tsx` is used, the error should be there. Because the `index` variable from `map` function hasn't been used. Providing the `div`s inside, the `key` prop with `index` value should fix it wherever it is used.
> 
> ![image](https://private-user-images.githubusercontent.com/27003616/295172039-15f90b3f-3af5-412f-a6be-65429ee8ce5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDY4NDgsIm5iZiI6MTcwNDgwNjU0OCwicGF0aCI6Ii8yNzAwMzYxNi8yOTUxNzIwMzktMTVmOTBiM2YtM2FmNS00MTJmLWE2YmUtNjU0MjllZThjZTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEzMjIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4Y2RiMzdiZjRmODMwYTAwNGFmOTAwYTdjYjk4MTg1YTY2MWY5ODkzNzBjM2YyYWI0MTZjMjdlOGVmYzYwMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rrG9kHnCQymTHrnAc34Qsg5pcxt0Ezazt6FlFlyhLyU)

yes

**Comment by a0m0rajab** [comment] 2024-01-09 13:30
@priyankarpal do you have a link on where you got the error?

**Comment by priyankarpal** [comment] 2024-01-09 14:08
> @priyankarpal do you have a link on where you got the error?

when you open the `insights` page you will see the errors. (development mode) 
- `components/atoms/SkeletonLoader/skeleton-wrapper.tsx` 
- `components/atoms/ClientOnly/client-only.tsx`
- `/pages/hub/insights/index.tsx`
- `layouts/hub.tsx`

**Comment by nickytonline** [comment] 2024-01-09 14:11
It's wherever the skeleton component is used, so the fix is in https://github.com/open-sauced/app/blob/72d678ed641f3782c23c49458dea33df004678c9/components/atoms/SkeletonLoader/skeleton-wrapper.tsx#L11-L26

This is most likely the fix unless a page is using the component itself multiple times.

```diff
const SkeletonWrapper = ({ classNames, count = 1, width, height, radius }: SkeletonWrapperProps): JSX.Element => {
  const skeletonArray = Array(count).fill(true);
  return (
    <>
      {skeletonArray.map((_, index) => {
        return !height ? (
-          <div className="react-loading-skeleton" />
+          <div key={index} className="react-loading-skeleton" />
        ) : (
-          <div className={classNames}>
+          <div key={index} className={classNames}>
            <Skeleton height={height} width={width} borderRadius={radius} count={1} />
          </div>
        );
      })}
    </>
  );
};
```

**Comment by Arol15** [comment] 2024-01-09 16:06
.take

**Comment by Arol15** [comment] 2024-01-09 16:33
@a0m0rajab @nickytonline I have done 2-3 good first issues already. Is it ok to do this one or should I leave it for someone who is looking for their first contribution? Should I be looking at other issues that don't have a first-issue label? Thank you for your time!

**Comment by ThePiyushAggarwal** [comment] 2024-01-09 17:41
I was wondering the same.

**Comment by nickytonline** [comment] 2024-01-09 19:15
Yeah, let's leave it for someone who hasn't contributed to the codebase yet.

**Comment by Alishow1111** [comment] 2024-01-09 22:00
Hi Guys, is it alright if i take this on as my first issue?

**Comment by Arol15** [comment] 2024-01-09 22:12
> Hi Guys, is it alright if i take this on as my first issue?

Of course! Go for it! Good luck! let us know if you need any help. Use `dot take` to assign it to yourself. Replace dot with `.`

**Comment by mjgoerlitz-new** [comment] 2024-01-09 22:22
. take

**Comment by Arol15** [comment] 2024-01-09 22:24
@mjgoerlitz-new i think @Alishow1111 wants to take it

**Comment by Alishow1111** [comment] 2024-01-09 22:25
.take

**Comment by manipandit** [comment] 2024-01-12 12:38
.take

**Comment by ThePiyushAggarwal** [comment] 2024-01-13 13:47
> @Alishow1111 The above solution definitely works, but you might want to use a unique ID for the index. Since the props do not supply one, you could do something like I have below.
> 
> ```
> import { v4 as uuidv4 } from 'uuid';
> 
> // ...
> 
> {skeletonArray.map((_, index) => {
>   const key = uuidv4();
>   return !height ? (
>     <div key={key} className="react-loading-skeleton" />
>   ) : (
>     <div key={key} className={classNames}>
>       <Skeleton key={key} height={height} width={width} borderRadius={radius} count={1} />
>     </div>
>   );
> })}
> ```

@krusecodes Using the `index` value from the `map` function is fine in this case as suggested [here](https://github.com/open-sauced/app/issues/2442#issuecomment-1883120232). You can read more on the concept in the [React docs](https://react.dev/learn/rendering-lists#why-does-react-need-keys)

**Comment by Alishow1111** [comment] 2024-01-13 13:55
HI guys, thanks. Sorry for the delay.

**Comment by nickytonline** [comment] 2024-01-13 14:23
Using the index is fine for this use case as @ThePiyushAggarwal mentioned.

**Comment by Nikhilh26** [comment] 2024-01-20 12:10
should i go ahead and do it? It wont take much time

**Comment by priyankarpal** [comment] 2024-01-21 04:15
> should i go ahead and do it? It wont take much time @ThePiyushAggarwal ?

Hello, this has already been assigned to someone

**Closed** 2024-02-01 21:52 UTC
Labels: good first issue, 🐛 bug
