### ISSUE TITLE
Bug: overflow x on the insight page

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/app#1417] opened 2023-07-24 20:49 UTC
### Describe the bug

https://github.com/open-sauced/landing-page/assets/72051159/cb78b3af-e53b-4248-82a3-55dbfdd8ead9

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/hub/insights
2. Swipe left and right
3. See error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment] 2023-07-24 21:27
Hey @dev-phantom, on what screen size is this detected?

**Comment by dev-phantom** [comment] 2023-07-24 21:42
> Hey @dev-phantom, on what screen size is this detected?

Mobile

**Comment by Jittojoyes98** [comment] 2023-07-27 06:47
Can i work on this ?

**Comment by kakashi2020** [comment] 2023-07-27 19:20
I can't reproduce this behavior on my mobile or using the dev tools.

**Comment by dev-phantom** [comment] 2023-07-27 19:28
> 

Then no need taking on this issue
I'm closing it in a bit

**Comment by dev-phantom** [comment] 2023-10-16 21:27
Reopening this issue as it still persist
Take this as a [reference](https://github.com/open-sauced/landing-page/issues/139#issuecomment-1655740186) to reproduce it

**Comment by JocheAttah** [comment] 2023-11-08 14:54
I would like to .take  this

**Comment by brandonroberts** [comment] 2024-03-01 20:06
Closing as resolved

**Closed by brandonroberts** 2024-03-01 20:06 UTC
Labels: good first issue, 🐛 bug
