### ISSUE TITLE
Bug: Broken link to image on "Welcome to Workspace"

### ISSUE THREAD

**Issue by adiati98** [open-sauced/app#2993] opened 2024-03-21 13:31 UTC
### Describe the bug

When we haven't create a workspace, we are welcomed by a "Welcome to Workspace" card that includes an image.
This image is not rendered on this card as shown in screenshot below.

![Screenshot 2024-03-21 142510](https://github.com/open-sauced/app/assets/45172775/df923522-ed64-490d-a4bc-2b26a3fb6cf8)

### Steps to reproduce

1. Go to "Your workspace" page. This page must be new (not having any list).
2. You will see the broken image on the prompt.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment] 2024-03-21 16:49
This is already fixed in beta. Duplicate of #2968.

**Closed by nickytonline** 2024-03-21 16:49 UTC
Labels: 🐛 bug, high-priority

**Comment by jpmcb** [comment] 2024-03-21 17:16
👍🏼 Thanks Nick! We're planning a release today, so should see this fixed on prod soon
