### ISSUE TITLE
Bug: Spam report isn't consistent on repo insights

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2781] opened 2024-02-27 15:25 UTC
### Describe the bug

The cards for spam and the table row, should show the same number. However that's not happening. 
<img width="1041" alt="Screenshot 2024-02-27 at 10 23 16 AM" src="https://github.com/open-sauced/app/assets/34313413/6caa1a24-9e56-4f9a-b88b-9c85771badff">

### Steps to reproduce

You can see it here https://app.opensauced.pizza/pages/BekahHW/1229/dashboard.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment] 2024-02-27 16:50
This probably has an inconsistency similar to what needed to be fixed in #2574 - looking into it now!

**Comment by jpmcb** [comment] 2024-02-27 17:39
I think the problem is that the UX is confusing:

![Screenshot 2024-02-27 at 10 36 11 AM](https://github.com/open-sauced/app/assets/23109390/9286c457-d170-4348-9cac-7c40ee439c2b)

After digging into the code, the big number in the card is actually the stat for "today" and the little number is yesterdays stat:

https://github.com/open-sauced/app/blob/41109a20f3669c2c9d8f4db9128c3d289155efbc/components/organisms/Dashboard/dashboard.tsx#L23-L24

and since we are generating those stats based on the pull requests histogram (where each bucket is a day), we are missing the 2 spam pull requests since they were from a few weeks ago:

![Screenshot 2024-02-27 at 10 34 35 AM](https://github.com/open-sauced/app/assets/23109390/89bda648-cd7d-40ea-b3df-1d2e06d5cca2)

I see a few paths forward:

1. We unify the stats from within the rows of repos and what appears in the card and update the cards to be a total of spam PRs. But maybe that isn't that useful: seeing a change over time from today --> yesterday could be more interesting than just seeing the totals of a range of time.
2. We make the cards more clear what they are displaying since there's not alot to show what exactly they are displaying.

cc @isabensusan

**Comment by BekahHW** [comment] 2024-02-28 20:39
@jpmcb I was under the impression that those cards should be showing numbers based on the selected filter (7 days, 30, 3mo).

Ok, digging into this a little further. Looks like contribs changes for 7 and 30, but not for 3mo. Nothing else seems to change though. And the tooltips say that it's over the selected time period. 

https://github.com/open-sauced/app/assets/34313413/1586efaa-fe04-4bc2-b9da-b680c80131b6

**Comment by jpmcb** [comment] 2024-02-29 02:24
Yeah, what's in code is inconsistent with what users expect or what we should be surfacing. We'll need some guidance from product on what these cards should be showing. We may also be removing these existing cards in favor of these KPIs implemented here: https://github.com/open-sauced/app/pull/2455

... but I'm not sure what the direction for all that should be.

**Comment by BekahHW** [comment] 2024-02-29 15:40
@jpmcb didn't realize that I had an issue opened that related back in Nov: [#2178](https://github.com/open-sauced/app/issues/2178)

**Comment by brandonroberts** [comment] 2024-02-29 17:41
We discussed this during our engineering meeting and will remove the spam metrics from repo insights for now and replace with a more relevant metric. Spam was only used more prominently during Hacktoberfest.

I would recommend opening a separate issue to remove it and closing this one.

**Closed** 2024-02-29 18:06 UTC
Labels: 🐛 bug, core team work
