### ISSUE TITLE
Bug: `Connect with github` not working in dev

### ISSUE THREAD

**Issue by Bitnagar** [open-sauced/app#1933] opened 2023-10-18 06:36 UTC
### Describe the bug

`Connect with github` not working in dev. See below:

https://github.com/open-sauced/app/assets/88842947/784f870c-4acc-4381-8c9d-deba927a0e04

Am i missing something?

### Steps to reproduce

1) Develop the app in codespaces.
2) Run the app and go to home page.
3) Click on `connect with github` and observe the issue.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

This is in development.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Bitnagar** [comment] 2023-10-18 06:52
I wanted to do something in the UI of this page https://app.opensauced.pizza/hub/insights , but can't access it on local/codespaces because i'm unable to login with github. What i am i missing? Help @brandonroberts @foxyblocks @gr2m @0-vortex

**Comment by ATREAY** [comment] 2023-10-18 10:07
I ran into the exact same problem when I tried running it locally, so any tips or help would be super appreciated!

**Comment by nickytonline** [comment] 2023-10-18 10:14
Duplicate of #1624.

**Closed** 2023-10-18 10:14 UTC
Labels: 🐛 bug, 👀 needs triage
