### ISSUE TITLE
Bug: Fix Subscribe Button Sticking Out of Container In Highlights Page

### ISSUE THREAD

**Issue by chhristopher** [open-sauced/app#1914] opened 2023-10-16 21:02 UTC
### Describe the bug

<img width="366" alt="Screenshot 2023-10-16 at 1 58 49 PM" src="https://github.com/open-sauced/app/assets/48575398/00959339-7a6b-4aa8-aa48-34d500dc7ede">

Subscribe button is bleeding out of its container.

### Steps to reproduce

1. Go to Highlights Page
2. View Subscribe Button
3. Resize browser window accordingly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment] 2023-10-16 21:25
Duplicate of #1729

**Closed by nickytonline** 2023-10-16 21:25 UTC
Labels: 🐛 bug, 👀 needs triage
