### ISSUE TITLE
Fix: Change Churned to Alumni 

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2111] opened 2023-11-10 20:28 UTC
We're currently using "Churned" and "Alumni" on the platform, but they both mean the same thing. We want to stay consistent by replacing "Churned" with "Alumni".

![image](https://github.com/open-sauced/app/assets/34313413/6d8ee370-1314-44e1-a44d-7bee94e0690b)

**Comment by nickytonline** [comment] 2023-11-10 20:38
Duplicate of #2109

**Closed by nickytonline** 2023-11-10 20:38 UTC
